### ISSUE TITLE
Canary Preview 8 Error

### ISSUE THREAD

**Issue by jalyons95** [nightingaleproject/vrdr-dotnet#377] opened 2023-02-07 16:23 UTC
When I run the exe for Canary Preview 8 and import an IJE string I receive the following error:
"Exception has been thrown by the target of an invocation".

Zip file with data and screenshots attached.
[Canary_Before_IJE.zip](https://github.com/nightingaleproject/vrdr-dotnet/files/10677292/Canary_Before_IJE.zip)

**Comment by johnarleyburns** [comment] 2023-02-10 19:12
Needs research to determine root cause and if this is a library or canary-specific issue.

**Comment by johnarleyburns** [comment] 2023-02-13 19:09
Found to be a canary issue, not a library issue, thus closing this one, opened a canary issue: https://github.com/nightingaleproject/canary/issues/114

**Closed by johnarleyburns** 2023-02-13 19:09 UTC
Labels: bug, needs investigation

**Comment by jalyons95** [comment] 2023-02-15 21:40
I still receive the same error using Preview 9 code of Canary.

![image](https://user-images.githubusercontent.com/58519809/219174337-e6a40cdf-045e-456b-b55d-dfc953cf5e6a.png)

**Comment by johnarleyburns** [comment] 2023-02-17 19:47
Mr. Lyons,

Please download the new release to fix this error:

v4.0.0-preview10

You will now see the full error message:

"Exception has been thrown by the target of an invocation.; Inner Exception
= [ NCHS ICD10 code 1R99 is invalid. ]"

To assist, I've also attached a fixed version of the IJE document with the
code 1R99 updated to R99, which then validates correctly.

Sincerely,
John Burns
